name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "*"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@6c5e34c2a874d32ed57f5ef4ff1522d42406f022 # main
    secrets: inherit
